# Python Programming basics

## Types and Functions

In [19]:
x = 1
y = 2
z = 3
x + y + z

6

Write a function that takes two numbers and adds them:

In [20]:
def add(x, y):
    return x + y

add(4, 6)

10

Extend the function to take an optional 3rd argument

In [21]:
def add(x, y, flag=0):
    #ADD YOUR CODE HERE
    return x+y+flag
    
print(add(1, 2))
print(add(4, 3, 5))

3
12

Extend the function to take another optional flag parameter and add only if it is true

In [22]:
def add(x, y, flag=0, flagoptional = False):
   
    if (flagoptional == True):
        return x+y+flag
    return

add(5,4,3,True)

12

Assign a function to a variable a

In [23]:
def add(x, y):
    return x+y;

a = add

a(1,2)

3

## Iterations in python

Create a list of 5 elements

In [24]:
list1 =[1 , 2, 3, 4, 5]

Square every item in the list using a loop inside the array index

In [25]:
for i in range(len(list1)):
    list1[i]=list1[i]*list1[i]
    
list1

[1, 4, 9, 16, 25]

Show how to use a iterator. First, use enumerate to create a new tuple from above list

In [29]:
new_list = enumerate(list1)
iterator = iter(new_list)

for i in range(len(list1)):
    print(next(iterator))

<enumerate object at 0x0000017BE895B9D8>
(0, 1)
(1, 4)
(2, 9)
(3, 16)
(4, 25)

Now use a zip iterator to do the same.

In [28]:
for i,j in zip(range(len(list1)),list1):
    print(i,j)

0 1
1 4
2 9
3 16
4 25

Now state the differences between a zip and enumerate iterator.

zip creates unique iterators per argument where iterator make single iterator.

## Strings in Python

Open the file poem.txt and print lenght of each line.

In [1]:
f=open("poem.txt","r")

list2=[]

for a in f.readlines():
    list2.append(len(a))
    
print(list2)
f.close()

[8, 26, 1, 23, 1, 1, 1, 1, 21, 1, 27, 59, 28, 27, 26, 21, 21, 23, 24, 17, 23, 10, 20, 19, 21, 31, 9, 27, 30, 11, 21, 26, 1, 50, 31, 1, 66, 12, 1, 17, 1, 1, 1, 7, 1, 49, 1, 48, 1, 5, 13, 1, 6, 44, 1, 5, 20, 1, 6, 10, 1, 5, 4, 1, 6, 40, 1, 5, 52, 1, 6, 47, 24, 1, 5, 26, 1, 6, 22, 1, 5, 18, 38, 45, 1, 6, 47, 1, 31, 1, 5, 24, 1, 5, 26, 1, 6, 21, 1, 5, 29, 23, 1, 6, 23, 21, 1, 8, 1, 5, 17, 1, 5, 5, 24, 1, 5, 16, 1, 5, 44, 1, 5, 46, 1, 5, 21, 1, 5, 35, 41, 47, 37, 44, 36, 41, 1, 5, 31, 1, 5, 17, 40, 41, 30, 1, 5, 19, 40, 1, 5, 19, 50, 50, 42, 29, 1, 5, 50, 1, 22, 1, 5, 47, 1, 5, 42, 1, 5, 46, 1, 5, 48, 1, 5, 22, 1, 5, 22, 1, 5, 49, 41, 39, 53, 1, 5, 16, 1, 5, 21, 1, 5, 41, 1, 14, 1, 5, 32, 1, 5, 45, 41, 21, 1, 5, 40, 37, 18, 1, 5, 25, 1, 5, 24, 35, 39, 44, 41, 14, 1, 5, 47, 46, 1, 5, 47, 43, 47, 1, 5, 48, 46, 42, 42, 40, 49, 42, 45, 49, 29, 1, 5, 12, 46, 41, 43, 44, 52, 52, 52, 35, 49, 44, 38, 42, 34, 49, 38, 48, 35, 46, 40, 38, 47, 41, 38, 45, 44, 40, 49, 43, 1, 5, 36, 46, 48, 44, 1, 5, 40, 42, 40, 50, 44, 49, 42, 46, 42, 47, 41, 38, 44, 37, 45, 1, 18, 1, 52, 41, 13, 39, 43, 13, 41, 39, 10, 38, 40, 52, 18, 52, 1, 5, 39, 1, 5, 26, 1, 5, 11, 1, 5, 11, 1, 5, 11, 1, 14, 1, 37, 34, 37, 38, 1, 5, 43, 1, 5, 41, 37, 43, 47, 42, 41, 39, 40, 36, 1, 5, 37, 45, 43, 44, 48, 50, 47, 41, 1, 5, 44, 44, 46, 41, 41, 38, 44, 46, 43, 1, 5, 44, 43, 1, 10, 1, 1, 1, 51, 1, 62, 34, 1, 6, 46, 45, 51, 37, 46, 41, 40, 46, 46, 42, 41, 51, 44, 41, 44, 45, 46, 38, 45, 43, 45, 46, 39, 43, 48, 46, 46, 40, 42, 43, 45, 45, 42, 41, 44, 40, 47, 33, 48, 1, 15, 46, 1, 6, 40, 1, 34, 1, 44, 46, 40, 53, 44, 42, 41, 45, 33, 1, 6, 15, 43, 48, 36, 41, 49, 48, 1, 6, 50, 1, 5, 46, 36, 40, 40, 1, 6, 44, 44, 40, 1, 5, 53, 1, 6, 45, 1, 5, 43, 1, 7, 42, 49, 37, 39, 52, 36, 1, 5, 25, 1, 7, 10, 38, 1, 5, 44, 43, 37, 40, 39, 40, 48, 47, 44, 43, 46, 1, 6, 51, 46, 47, 52, 36, 42, 37, 45, 42, 39, 40, 43, 39, 42, 47, 45, 42, 47, 47, 47, 39, 44, 42, 34, 45, 40, 39, 37, 38, 42, 44, 1, 7, 45, 48, 1, 5, 40, 1, 6, 37, 40, 42, 44, 44, 47, 51, 40, 1, 25, 1, 5, 44, 37, 38, 48, 41, 39, 42, 52, 48, 49, 40, 45, 45, 46, 44, 37, 46, 54, 44, 46, 45, 47, 53, 48, 36, 43, 42, 45, 42, 39, 48, 1, 42, 1, 5, 23, 1, 5, 27, 33, 1, 5, 47, 1, 5, 53, 46, 11, 1, 5, 16, 1, 5, 46, 46, 1, 5, 36, 1, 5, 36, 39, 38, 44, 37, 46, 1, 5, 46, 1, 5, 42, 43, 1, 5, 40, 1, 5, 49, 46, 41, 40, 38, 1, 5, 16, 1, 5, 27, 1, 5, 38, 1, 5, 39, 38, 1, 5, 40, 1, 5, 9, 1, 5, 31, 1, 5, 20, 1, 5, 34, 40, 37, 20, 1, 5, 28, 1, 5, 41, 39, 42, 50, 34, 42, 48, 44, 54, 38, 45, 37, 48, 44, 49, 42, 31, 1, 5, 20, 1, 5, 45, 1, 5, 25, 1, 5, 16, 44, 38, 42, 42, 42, 29, 1, 5, 19, 1, 5, 43, 42, 23, 1, 5, 44, 29, 1, 14, 16, 1, 5, 16, 1, 6, 16, 1, 5, 17, 1, 6, 28, 1, 5, 27, 1, 5, 40, 1, 5, 28, 1, 5, 44, 1, 5, 13, 1, 5, 16, 1, 5, 29, 1, 5, 17, 1, 5, 26, 1, 5, 31, 1, 5, 38, 1, 5, 52, 1, 14, 16, 1, 5, 18, 1, 5, 29, 1, 5, 39, 18, 1, 5, 23, 29, 1, 5, 19, 1, 5, 39, 49, 42, 43, 41, 40, 41, 45, 45, 16, 1, 5, 25, 1, 5, 38, 1, 43, 1, 45, 51, 52, 52, 1, 8, 1, 1, 1, 39, 1, 29, 1, 6, 39, 39, 39, 26, 1, 5, 19, 1, 6, 44, 39, 39, 44, 40, 9, 1, 5, 16, 1, 6, 18, 42, 45, 40, 45, 41, 43, 48, 40, 36, 45, 43, 47, 41, 54, 41, 38, 46, 44, 45, 44, 49, 31, 43, 44, 38, 37, 38, 45, 43, 43, 40, 41, 40, 47, 1, 5, 44, 47, 39, 44, 46, 46, 28, 1, 6, 16, 44, 1, 18, 1, 37, 37, 1, 5, 46, 44, 55, 1, 37, 1, 37, 50, 40, 42, 51, 48, 44, 47, 41, 44, 45, 51, 39, 45, 39, 48, 44, 36, 43, 43, 44, 42, 41, 43, 1, 6, 41, 1, 5, 46, 1, 6, 37, 25, 1, 5, 26, 43, 1, 6, 10, 1, 8, 1, 5, 41, 1, 5, 51, 1, 5, 23, 38, 44, 52, 36, 45, 42, 44, 43, 1, 5, 44, 24, 1, 5, 46, 40, 46, 1, 5, 45, 1, 5, 46, 48, 53, 47, 44, 1, 5, 41, 23, 1, 5, 43, 1, 5, 51, 41, 1, 5, 44, 44, 47, 47, 44, 43, 46, 39, 43, 42, 37, 40, 49, 46, 38, 43, 42, 50, 39, 47, 41, 1, 5, 23, 1, 10, 1, 1, 1, 24, 1, 40, 1, 5, 41, 1, 5, 34, 1, 5, 15, 1, 5, 28, 1, 5, 18, 1, 5, 51, 42, 1, 56, 1, 30, 1, 5, 49, 51, 48, 42, 27, 1, 5, 16, 1, 5, 17, 42, 40, 49, 38, 46, 49, 41, 51, 38, 36, 47, 49, 41, 38, 49, 45, 49, 42, 44, 47, 34, 45, 45, 41, 20, 1, 5, 25, 1, 15, 1, 5, 43, 45, 54, 37, 41, 50, 40, 40, 43, 47, 38, 40, 43, 48, 42, 45, 37, 47, 48, 1, 24, 1, 5, 35, 36, 14, 1, 5, 32, 39, 23, 1, 5, 17, 1, 5, 42, 1, 5, 17, 1, 5, 30, 37, 41, 34, 42, 1, 5, 48, 39, 41, 42, 48, 40, 41, 38, 37, 27, 1, 5, 21, 25, 1, 5, 27, 1, 5, 21, 1, 5, 28, 1, 5, 19, 41, 39, 1, 17, 1, 44, 1, 27, 1, 52, 39, 1, 27, 1, 5, 37, 1, 5, 45, 1, 5, 43, 1, 5, 45, 1, 5, 23, 1, 5, 23, 1, 10, 1, 1, 1, 43, 1, 26, 1, 5, 54, 1, 7, 9, 1, 5, 8, 1, 7, 24, 43, 23, 1, 5, 18, 1, 7, 42, 24, 1, 5, 27, 1, 7, 46, 1, 5, 6, 1, 7, 26, 45, 43, 47, 48, 40, 42, 50, 57, 40, 41, 40, 36, 52, 42, 1, 5, 7, 1, 7, 44, 1, 5, 8, 1, 7, 40, 44, 1, 5, 48, 39, 25, 1, 7, 17, 46, 41, 50, 45, 48, 35, 43, 45, 21, 1, 5, 21, 12, 1, 7, 44, 53, 44, 40, 44, 40, 40, 44, 42, 44, 18, 39, 47, 43, 36, 21, 44, 46, 35, 37, 40, 39, 38, 39, 47, 42, 40, 42, 46, 40, 47, 20, 43, 49, 40, 36, 42, 38, 41, 42, 36, 38, 39, 46, 47, 45, 48, 41, 40, 35, 1, 8, 1, 5, 46, 50, 42, 40, 47, 41, 33, 41, 50, 41, 41, 40, 45, 25, 45, 38, 49, 46, 1, 11, 1, 42, 35, 16, 1, 5, 30, 1, 5, 25, 1, 5, 29, 1, 5, 10, 1, 5, 33, 1, 5, 38, 1, 31, 1, 5, 25, 1, 5, 20, 1, 5, 14, 1, 5, 23, 1, 5, 22, 1, 5, 27, 1, 5, 16, 1, 5, 54, 22, 1, 14, 24, 1, 5, 48, 26, 1, 5, 51, 17, 1, 5, 34, 42, 44, 53, 40, 42, 24, 1, 5, 48, 1, 5, 37, 22, 1, 5, 29, 1, 5, 46, 51, 45, 44, 48, 44, 26, 1, 5, 29, 1, 5, 46, 1, 14, 22, 1, 5, 18, 1, 5, 10, 16, 1, 5, 26, 1, 5, 15, 1, 5, 33, 1, 5, 31, 1, 7, 18, 1, 5, 57, 51, 18, 1, 5, 27, 1, 5, 43, 19, 1, 7, 18, 1, 5, 46, 24, 40, 44, 19, 1, 7, 18, 1, 5, 54, 50, 1, 5, 47, 1, 5, 45, 52, 39, 12, 43, 43, 44, 34, 48, 47, 43, 59, 61, 38, 47, 47, 7, 1, 7, 18, 1, 5, 46, 41, 36, 50, 52, 45, 43, 40, 30, 1, 10, 1, 1, 1, 8, 1, 37, 1, 31, 1, 5, 47, 1, 5, 17, 1, 5, 47, 38, 18, 1, 5, 26, 1, 5, 49, 45, 51, 44, 45, 47, 44, 52, 45, 46, 1, 5, 24, 1, 5, 49, 39, 42, 47, 41, 45, 39, 22, 1, 5, 20, 1, 5, 49, 30, 1, 5, 35, 1, 5, 47, 41, 33, 58, 42, 40, 35, 20, 1, 5, 21, 1, 5, 30, 1, 5, 13, 19, 1, 5, 29, 40, 42, 50, 10, 45, 43, 44, 40, 49, 40, 20, 1, 5, 20, 1, 5, 66, 63, 1, 5, 55, 12, 1, 5, 43, 49, 37, 55, 48, 44, 42, 38, 13, 49, 39, 41, 37, 37, 45, 1, 5, 17, 1, 5, 31, 1, 5, 14, 1, 5, 37, 1, 5, 18, 1, 5, 27, 1, 5, 15, 1, 5, 10, 1, 17, 1, 17, 1, 37, 1, 5, 42, 1, 5, 31, 1, 5, 40, 45, 44, 41, 50, 38, 37, 42, 1, 5, 18, 1, 5, 24, 24, 1, 5, 14, 1, 5, 43, 43, 44, 36, 40, 40, 47, 41, 39, 45, 44, 44, 45, 42, 1, 5, 43, 34, 39, 46, 35, 45, 49, 1, 5, 43, 35, 18, 1, 5, 24, 46, 50, 50, 33, 41, 37, 45, 56, 44, 1, 10, 1, 1, 1, 32, 1, 57, 1, 6, 44, 43, 40, 44, 42, 42, 42, 53, 43, 38, 50, 50, 47, 39, 44, 40, 49, 38, 1, 7, 44, 43, 47, 40, 39, 39, 42, 30, 1, 5, 20, 46, 43, 18, 1, 6, 14, 46, 40, 17, 1, 6, 45, 1, 7, 45, 37, 43, 43, 1, 6, 44, 29, 1, 7, 10, 1, 57, 1, 18, 1, 5, 43, 23, 1, 6, 46, 1, 5, 44, 35, 40, 44, 38, 42, 35, 1, 6, 42, 1, 5, 42, 48, 1, 6, 45, 1, 17, 1, 43, 49, 1, 7, 39, 47, 1, 6, 25, 1, 48, 1, 26, 46, 1, 6, 43, 40, 43, 40, 40, 49, 41, 46, 42, 43, 38, 48, 39, 47, 45, 41, 40, 17, 44, 44, 40, 25, 1, 6, 18, 44, 38, 49, 48, 19, 1, 34, 1, 5, 31, 37, 38, 50, 48, 45, 50, 41, 43, 42, 17, 1, 7, 28, 1, 5, 36, 48, 43, 40, 43, 43, 41, 42, 41, 9, 47, 38, 45, 9, 59, 12, 60, 34, 9, 43, 1, 7, 30, 1, 5, 45, 9, 34, 35, 29, 29, 62, 66, 11, 66, 14, 48, 38, 47, 23, 1, 6, 17, 19, 1, 5, 25, 1, 6, 37, 1, 5, 49, 45, 41, 46, 43, 40, 44, 44, 48, 42, 45, 49, 46, 40, 46, 43, 39, 43, 48, 39, 21, 1, 6, 24, 1, 7, 24, 1, 5, 51, 39, 26, 1, 6, 17, 1, 5, 43, 35, 38, 46, 19, 1, 6, 27, 1, 5, 47, 19, 1, 7, 19, 1, 5, 46, 35, 40, 42, 36, 29, 1, 6, 16, 1, 7, 52, 1, 5, 34, 45, 1, 38, 1, 25, 1, 30, 1, 5, 19, 1, 5, 25, 1, 5, 37, 1, 5, 16, 1, 5, 39, 1, 5, 17, 1, 5, 60, 28, 1, 5, 27, 1, 5, 64, 31, 1, 5, 17, 1, 5, 63, 51, 1, 5, 66, 63, 64, 64, 15, 1, 5, 21, 1, 5, 29, 1, 5, 13, 1, 5, 43, 1, 5, 62, 60, 60, 64, 66, 61, 63, 1, 5, 63, 39, 1, 5, 15, 1, 5, 64, 63, 63, 66, 66, 17, 1, 5, 56, 66, 6, 1, 5, 24, 1, 5, 25, 1, 38, 1, 5, 45, 1, 5, 34, 1, 17, 1, 6, 18, 1, 5, 19, 1, 5, 60, 40, 1, 5, 42, 1, 6, 37, 45, 1, 5, 27, 1, 5, 18, 1, 5, 55, 9, 1, 6, 24, 1, 5, 55, 27, 1, 5, 50, 1, 5, 57, 61, 63, 8, 1, 6, 17, 1, 5, 20, 1, 5, 23, 1, 5, 59, 42, 1, 5, 26, 1, 5, 61, 55, 1, 5, 64, 6, 1, 5, 60, 60, 1, 6, 62, 47, 1, 5, 32, 1, 5, 63, 29, 1, 5, 63, 63, 22, 1, 16, 21, 1, 5, 56, 61, 64, 22, 1, 5, 42, 1, 5, 61, 65, 57, 63, 1, 6, 29, 1, 5, 58, 66, 64, 19, 1, 5, 22, 1, 5, 62, 58, 63, 65, 37, 1, 5, 33, 1, 5, 64, 9, 1, 6, 27, 1, 5, 59, 59, 65, 63, 63, 66, 65, 63, 64, 59, 61, 63, 66, 65, 52, 1, 5, 49, 1, 5, 59, 1, 5, 58, 64, 61, 1, 5, 60, 66, 64, 62, 62, 62, 6, 1, 5, 55, 24, 1, 5, 53, 45, 1, 5, 56, 12, 1, 5, 60, 28, 1, 5, 26, 1, 5, 34, 1, 5, 61, 65, 64, 66, 64, 26, 1, 5, 57, 62, 56, 66, 65, 30, 1, 5, 63, 61, 65, 31, 1, 5, 15, 1, 6, 49, 1, 5, 27, 1, 5, 54, 1, 5, 61, 64, 66, 66, 30, 1, 31, 1, 6, 23, 1, 5, 62, 63, 62, 59, 63, 30, 1, 6, 23, 1, 5, 60, 28, 1, 18, 1, 5, 29, 1, 5, 66, 65, 1, 5, 63, 22, 1, 5, 66, 52, 1, 5, 34, 1, 5, 63, 8, 1, 5, 37, 1, 5, 12, 1, 5, 18, 1, 5, 35, 1, 5, 58, 58, 65, 63, 66, 14, 1, 5, 57, 1, 5, 31, 1, 5, 6, 36, 37, 1, 1, 5, 31, 1, 5, 37, 1, 5, 59, 19, 1, 5, 23, 1, 5, 29, 1, 5, 6, 25, 20, 44, 64, 27, 1, 30, 1, 63, 61, 59, 60, 62, 61, 66, 59, 63, 50, 1, 8, 22, 1, 5, 62, 64, 65, 66, 66, 63, 63, 60, 61, 66, 66, 63, 60, 1, 48, 1, 42, 1, 45, 48, 47, 52, 43, 43, 52, 49, 44, 53, 43, 50, 31, 1, 17, 1, 5, 59, 12, 1, 8, 22, 52, 47, 42, 50, 49, 52, 47, 48, 51, 41, 50, 43, 47, 16, 44, 51, 48, 47, 51, 43, 43, 46, 50, 25, 51, 42, 52, 52, 28, 1, 5, 18, 1, 5, 63, 64, 11, 1, 8, 48, 1, 5, 20, 1, 5, 37, 1, 8, 52, 45, 48, 44, 48, 52, 58, 48, 45, 50, 49, 48, 53, 28, 1, 5, 63, 26, 1, 5, 61, 61, 66, 64, 50, 1, 5, 52, 1, 5, 52, 63, 64, 27, 1, 5, 12, 1, 5, 50, 1, 54, 1, 59, 10, 1, 8, 13, 1, 5, 59, 65, 28, 1, 8, 13, 1, 5, 57, 1, 21, 1, 60, 36, 1, 5, 14, 1, 39, 1, 5, 23, 16, 40, 43, 41, 43, 44, 44, 47, 48, 12, 39, 47, 42, 49, 47, 41, 42, 37, 7, 39, 44, 40, 39, 41, 45, 45, 54, 47, 45, 39, 39, 42, 48, 55, 14, 43, 43, 43, 47, 37, 12, 48, 42, 38, 42, 41, 49, 52, 44, 43, 46, 46, 43, 45, 40, 42, 40, 47, 47, 1, 8, 1, 1, 1, 1, 9, 1, 31, 1, 56, 15, 1, 6, 42, 44, 41, 37, 1, 5, 45, 47, 1, 6, 42, 40, 46, 19, 1, 7, 25, 1, 5, 23, 1, 6, 42, 1, 5, 42, 24, 1, 7, 18, 16, 1, 5, 43, 49, 40, 41, 41, 31, 1, 5, 16, 46, 28, 1, 6, 47, 27, 41, 44, 1, 5, 19, 1, 39, 1, 6, 30, 44, 41, 17, 42, 47, 41, 37, 41, 26, 1, 7, 20, 38, 43, 51, 40, 22, 1, 5, 22, 1, 14, 1, 5, 50, 60, 41, 49, 51, 34, 19, 1, 6, 27, 54, 50, 44, 41, 16, 1, 5, 44, 1, 28, 1, 16, 1, 5, 46, 42, 44, 43, 48, 38, 47, 44, 44, 52, 49, 44, 40, 37, 49, 50, 45, 40, 42, 39, 50, 39, 47, 43, 41, 44, 40, 45, 38, 48, 42, 44, 44, 41, 27, 1, 5, 14, 42, 1, 5, 38, 1, 5, 38, 39, 30, 1, 5, 11, 24, 1, 5, 47, 48, 50, 40, 46, 16, 1, 5, 24, 1, 5, 9, 1, 5, 14, 1, 5, 26, 1, 5, 61, 26, 1, 5, 63, 1, 5, 57, 64, 65, 54, 1, 5, 41, 1, 5, 54, 63, 5, 1, 5, 25, 1, 5, 56, 64, 66, 65, 62, 66, 65, 59, 8, 1, 5, 18, 1, 5, 58, 38, 1, 5, 32, 1, 5, 64, 65, 63, 62, 62, 10, 1, 5, 32, 1, 5, 58, 66, 65, 66, 62, 65, 28, 1, 8, 1, 5, 41, 58, 43, 44, 51, 42, 41, 46, 49, 47, 36, 47, 1, 30, 1, 6, 43, 51, 52, 41, 42, 43, 30, 50, 41, 41, 35, 44, 47, 46, 1, 5, 39, 41, 47, 44, 45, 40, 43, 46, 46, 46, 42, 30, 1, 6, 16, 45, 1, 10, 1, 1, 1, 32, 1, 36, 1, 5, 57, 63, 64, 59, 61, 51, 64, 66, 66, 64, 66, 51, 1, 10, 23, 1, 5, 61, 65, 62, 65, 62, 63, 63, 65, 59, 61, 64, 64, 58, 63, 59, 63, 24, 1, 10, 57, 1, 5, 61, 62, 62, 63, 64, 63, 16, 1, 18, 1, 49, 1, 57, 1, 5, 39, 1, 5, 28, 1, 17, 1, 34, 1, 15, 18, 1, 24, 1, 5, 19, 1, 17, 1, 5, 35, 1, 5, 37, 38, 1, 5, 19, 1, 5, 29, 43, 44, 59, 45, 42, 49, 47, 43, 49, 48, 41, 51, 48, 46, 48, 49, 46, 45, 42, 45, 46, 46, 39, 42, 38, 40, 32, 43, 40, 44, 27, 1, 5, 15, 51, 43, 1, 5, 45, 17, 1, 65, 40, 1, 6, 29, 1, 5, 61, 44, 1, 6, 61, 6, 1, 5, 66, 20, 1, 5, 53, 1, 5, 20, 1, 5, 63, 11, 1, 5, 64, 19, 1, 5, 43, 1, 7, 40, 1, 5, 47, 1, 5, 40, 1, 5, 31, 32, 1, 5, 13, 1, 5, 31, 1, 5, 13, 1, 5, 38, 1, 5, 26, 1, 5, 50, 1, 5, 18, 1, 5, 9, 1, 5, 24, 1, 5, 8, 1, 5, 13, 1, 5, 59, 64, 21, 1, 5, 37, 1, 5, 61, 65, 65, 66, 61, 56, 1, 40, 1, 61, 59, 58, 56, 62, 65, 65, 60, 63, 66, 42, 1, 10, 1, 5, 26, 1, 5, 52, 1, 5, 51, 1, 18, 1, 5, 63, 18, 1, 5, 38, 1, 5, 60, 49, 1, 5, 52, 1, 5, 32, 35, 34, 1, 5, 43, 1, 5, 21, 1, 5, 17, 1, 28, 1, 9, 48, 46, 43, 49, 48, 38, 1, 10, 38, 43, 41, 46, 45, 42, 42, 35, 48, 40, 51, 55, 1, 9, 49, 47, 47, 41, 26, 1, 10, 22, 46, 37, 46, 1, 5, 29, 1, 10, 40, 47, 37, 38, 1, 9, 43, 39, 36, 37, 50, 39, 35, 44, 41, 43, 36, 45, 47, 46, 48, 53, 42, 49, 50, 44, 40, 45, 42, 32, 37, 39, 39, 51, 42, 50, 1, 10, 45, 45, 39, 41, 42, 45, 46, 34, 1, 5, 42, 1, 9, 48, 47, 28, 10, 1, 10, 22, 43, 1, 8, 1, 5, 31, 1, 7, 38, 1, 5, 29, 1, 6, 55, 1, 5, 60, 7, 1, 6, 27, 1, 5, 57, 62, 64, 60, 65, 13, 1, 18, 1, 42, 1, 5, 32, 1, 5, 60, 22, 1, 5, 37, 1, 5, 50, 1, 5, 25, 1, 5, 61, 63, 21, 1, 5, 57, 45, 48, 51, 36, 37, 1, 44, 1, 5, 63, 61, 65, 1, 5, 16, 1, 5, 32, 1, 7, 19, 1, 5, 20, 1, 6, 27, 1, 5, 24, 1, 37, 1, 5, 39, 29, 47, 31, 65, 61, 59, 1, 5, 14, 1, 5, 21, 37, 31, 40, 27, 1, 5, 23, 1, 5, 58, 23, 1, 5, 20, 1, 5, 34, 1, 5, 26, 1, 5, 50, 40, 44, 18, 1, 38, 1, 6, 44, 1, 5, 22, 1, 6, 16, 1, 5, 22, 1, 6, 47, 1, 5, 17, 1, 6, 33, 1, 5, 62, 61, 33, 1, 6, 60, 30, 1, 5, 28, 1, 6, 60, 21, 1, 5, 17, 1, 6, 60, 64, 61, 33, 1, 5, 15, 1, 6, 15, 1, 5, 63, 64, 64, 7, 1, 5, 56, 26, 1, 5, 64, 49, 1, 5, 63, 1, 5, 59, 23, 1, 5, 31, 1, 5, 50, 1, 5, 63, 62, 13, 1, 5, 25, 1, 5, 61, 32, 1, 5, 63, 7, 1, 40, 1, 66, 65, 13, 1, 6, 62, 1, 5, 61, 1, 6, 19, 1, 5, 12, 1, 6, 22, 1, 5, 18, 1, 6, 33, 1, 5, 55, 62, 62, 1, 6, 58, 20, 1, 5, 60, 63, 62, 63, 62, 64, 64, 25, 1, 18, 1, 20, 1, 5, 56, 1, 5, 59, 1, 5, 43, 1, 5, 30, 1, 5, 28, 1, 5, 17, 1, 5, 19, 1, 5, 62, 40, 1, 5, 15, 1, 8, 1, 5, 26, 1, 17, 1, 21, 1, 40, 1, 42, 52, 54, 39, 50, 43, 40, 32, 43, 44, 38, 44, 1, 8, 1, 1, 1, 33, 1, 45, 1, 6, 43, 49, 43, 40, 39, 38, 21, 1, 6, 27, 35, 36, 38, 1, 5, 39, 46, 44, 44, 40, 42, 45, 42, 48, 49, 41, 41, 45, 1, 6, 44, 40, 32, 1, 14, 18, 1, 24, 1, 18, 1, 5, 44, 36, 55, 42, 49, 49, 49, 38, 26, 1, 6, 22, 1, 17, 1, 44, 42, 37, 40, 44, 42, 44, 43, 49, 46, 47, 39, 47, 39, 43, 46, 48, 43, 47, 43, 44, 40, 44, 42, 41, 46, 48, 46, 44, 42, 40, 42, 43, 44, 56, 40, 17, 1, 22, 1, 16, 1, 5, 42, 46, 46, 41, 43, 11, 41, 42, 50, 49, 47, 47, 40, 45, 4, 45, 41, 42, 39, 40, 50, 45, 43, 42, 1, 8, 1, 31, 1, 6, 43, 43, 1, 8, 1, 1, 1, 38, 1, 28, 1, 5, 49, 54, 52, 46, 29, 1, 5, 34, 1, 7, 18, 43, 1, 34, 1, 16, 1, 5, 32, 1, 7, 44, 1, 5, 42, 1, 7, 44, 1, 5, 43, 1, 7, 22, 1, 5, 23, 1, 7, 20, 1, 5, 25, 50, 48, 1, 7, 49, 1, 5, 51, 37, 42, 1, 7, 46, 16, 1, 5, 38, 1, 5, 25, 24, 1, 34, 1, 5, 25, 1, 18, 1, 7, 27, 1, 5, 33, 1, 24, 1, 7, 40, 1, 5, 44, 43, 1, 7, 16, 1, 5, 27, 47, 15, 46, 46, 51, 45, 35, 39, 44, 1, 7, 50, 29, 1, 5, 12, 43, 43, 44, 46, 42, 39, 40, 46, 38, 43, 28, 1, 7, 17, 47, 1, 5, 44, 45, 42, 45, 43, 34, 38, 34, 42, 38, 51, 43, 47, 47, 44, 41, 47, 47, 53, 52, 41, 43, 40, 48, 45, 45, 47, 39, 19, 46, 42, 39, 44, 45, 42, 25, 1, 7, 25, 42, 45, 31, 1, 5, 17, 38, 47, 22, 1, 7, 24, 45, 23, 1, 5, 26, 45, 41, 39, 44, 26, 1, 7, 9, 1, 5, 32, 1, 15, 1, 43, 55, 1, 7, 16, 1, 5, 41, 45, 44, 8, 1, 7, 31, 43, 41, 45, 45, 22, 1, 5, 26, 1, 7, 25, 38, 47, 45, 44, 44, 41, 41, 45, 1, 5, 45, 51, 47, 42, 41, 50, 1, 7, 27, 1, 5, 26, 1, 7, 39, 1, 5, 26, 1, 7, 27, 1, 5, 46, 37, 49, 1, 14, 1, 7, 40, 31, 20, 1, 5, 9, 48, 48, 43, 45, 46, 45, 47, 46, 43, 44, 43, 44, 48, 40, 39, 44, 1, 7, 45, 1, 5, 37, 40, 44, 37, 45, 40, 41, 36, 40, 39, 44, 47, 44, 46, 40, 46, 24, 44, 42, 43, 40, 46, 34, 45, 26, 1, 7, 17, 1, 5, 42, 43, 48, 42, 50, 39, 38, 48, 47, 41, 45, 37, 37, 45, 40, 30, 1, 7, 45, 46, 27, 1, 5, 34, 1, 7, 7, 36, 1, 5, 52, 45, 46, 40, 39, 48, 44, 47, 45, 31, 45, 45, 48, 41, 45, 20, 1, 51, 1, 1, 1, 8, 1, 31, 1, 51, 1, 6, 53, 49, 19, 1, 7, 40, 1, 47, 1, 45, 1, 6, 33, 1, 7, 43, 42, 41, 44, 41, 25, 1, 6, 14, 43, 39, 38, 46, 40, 53, 45, 43, 39, 39, 44, 1, 7, 39, 42, 32, 46, 1, 6, 23, 44, 47, 39, 48, 1, 41, 1, 49, 39, 50, 48, 44, 1, 39, 1, 50, 42, 46, 41, 37, 50, 42, 39, 1, 10, 1, 38, 1, 16, 1, 5, 15, 1, 15, 31, 1, 5, 52, 1, 38, 1, 5, 49, 1, 5, 43, 1, 5, 48, 27, 1, 5, 19, 1, 5, 14, 1, 5, 63, 66, 11, 1, 5, 35, 1, 5, 60, 63, 63, 65, 64, 7, 1, 5, 31, 1, 5, 59, 1, 5, 62, 10, 1, 5, 62, 23, 1, 6, 18, 1, 5, 54, 1, 10, 1, 1, 1, 39, 1, 23, 1, 6, 46, 46, 43, 40, 48, 54, 52, 39, 43, 37, 15, 1, 21, 1, 29, 1, 5, 42, 24, 1, 6, 17, 1, 5, 50, 1, 6, 21, 1, 5, 36, 1, 33, 1, 6, 31, 1, 5, 11, 1, 6, 18, 1, 5, 52, 64, 64, 65, 63, 9, 1, 6, 12, 1, 5, 62, 40, 1, 6, 29, 1, 5, 61, 22, 1, 6, 19, 1, 5, 63, 65, 64, 27, 1, 6, 41, 1, 5, 28, 1, 21, 1, 6, 48, 40, 53, 49, 41, 44, 13, 1, 5, 13, 1, 6, 12, 1, 5, 6, 1, 6, 40, 1, 5, 58, 23, 1, 6, 27, 1, 5, 62, 50, 1, 8, 1, 6, 49, 44, 40, 53, 1, 39, 1, 50, 47, 42, 41, 46, 46, 37, 45, 42, 46, 43, 1, 8, 1, 1, 1, 30, 1, 41, 1, 5, 44, 42, 42, 43, 41, 38, 21, 1, 6, 22, 1, 5, 14, 1, 30, 1, 47, 1, 5, 34, 1, 6, 25, 1, 5, 31, 1, 6, 29, 1, 5, 24, 1, 6, 38, 1, 5, 41, 22, 1, 6, 38, 39, 40, 47, 40, 41, 1, 5, 43, 1, 6, 31, 1, 5, 46, 44, 49, 47, 44, 1, 6, 21, 1, 8, 1, 5, 31, 1, 5, 47, 1, 25, 1, 39, 41, 41, 44, 48, 38, 35, 41, 41, 42, 53, 44, 44, 53, 46, 44, 37, 43, 37, 35, 45, 43, 39, 39, 47, 45, 39, 45, 42, 39, 47, 42, 39, 45, 44, 1, 8, 1, 1, 1, 41, 1, 27, 1, 7, 27, 1, 6, 37, 31, 1, 7, 21, 1, 6, 46, 60, 52, 50, 37, 43, 50, 56, 52, 41, 52, 45, 1, 7, 17, 1, 16, 1, 42, 45, 38, 41, 1, 33, 1, 5, 43, 1, 7, 18, 1, 14, 36, 23, 32, 27, 1, 7, 42, 1, 5, 30, 9, 30, 26, 35, 27, 1, 7, 19, 1, 5, 16, 9, 42, 1, 14, 1, 7, 26, 1, 5, 9, 36, 36, 29, 1, 6, 25, 1, 5, 61, 66, 12, 1, 6, 25, 1, 5, 66, 24, 9, 38, 33, 32, 27, 1, 43, 34, 36, 26, 1, 6, 16, 1, 5, 52, 9, 32, 31, 42, 33, 1, 37, 29, 39, 39, 1, 6, 29, 1, 5, 58, 65, 62, 65, 32, 1, 8, 1, 6, 51, 1, 16, 1, 48, 51, 47, 44, 48, 44, 57, 55, 44, 44, 50, 43, 43, 46, 40, 47, 39, 41, 42, 42, 28, 1, 18, 1, 7, 27, 1, 6, 48, 1, 21, 1, 20, 1, 6, 24, 36, 45, 39, 50, 41, 36, 39, 45, 51, 39, 1, 7, 44, 43, 1, 18, 1, 6, 21, 1, 41, 1, 6, 50, 1, 7, 19, 1, 6, 27, 1, 7, 18, 1, 32, 1, 6, 48, 19, 1, 7, 22, 1, 6, 53, 46, 46, 19, 1, 6, 28, 42, 46, 41, 44, 44, 53, 12, 1, 6, 20, 1, 6, 6, 1, 7, 16, 1, 6, 25, 1, 6, 44, 50, 46, 44, 44, 43, 30, 1, 6, 20, 1, 6, 28, 45, 31, 1, 6, 14, 36, 55, 53, 18, 1, 6, 22, 1, 6, 25, 1, 6, 48, 43, 27, 1, 6, 19, 40, 44, 38, 42, 25, 1, 7, 26, 1, 6, 29, 1, 57, 10, 1, 50, 45, 48, 45, 41, 45, 42, 45, 42, 26, 1, 5, 9, 39, 34, 42, 1, 24, 1, 6, 49, 24, 1, 5, 58, 66, 19, 1, 6, 33, 1, 5, 54, 53, 1, 6, 57, 1, 5, 62, 57, 66, 66, 48, 9, 42, 1, 6, 46, 39, 1, 5, 9, 31, 31, 25, 26, 29, 1, 35, 28, 29, 28, 30, 1, 56, 1, 8, 1, 6, 24, 1, 6, 41, 36, 50, 49, 35, 48, 48, 36, 44, 43, 24, 1, 6, 16, 42, 48, 40, 49, 32, 1, 6, 14, 49, 23, 1, 10, 1, 1, 1, 38, 1, 31, 1, 5, 40, 1, 9, 50, 1, 5, 18, 1, 16, 1, 42, 46, 1, 17, 1, 10, 20, 1, 5, 24, 1, 8, 58, 66, 49, 1, 5, 51, 59, 62, 62, 65, 62, 66, 66, 65, 65, 65, 64, 64, 57, 43, 1, 50, 46, 35, 1, 10, 1, 1, 1, 39, 1, 26, 1, 6, 46, 46, 45, 43, 17, 1, 6, 30, 43, 38, 44, 28, 1, 6, 28, 48, 52, 45, 46, 42, 47, 42, 38, 47, 48, 51, 48, 42, 37, 32, 1, 6, 35, 40, 43, 41, 48, 1, 6, 52, 43, 48, 51, 42, 47, 1, 21, 1, 20, 1, 6, 31, 41, 1, 6, 31, 1, 6, 44, 49, 26, 1, 6, 30, 10, 1, 18, 1, 64, 62, 62, 63, 1, 51, 40, 1, 6, 19, 1, 6, 37, 43, 19, 1, 6, 44, 39, 45, 20, 1, 6, 24, 41, 25, 1, 6, 13, 40, 1, 6, 44, 45, 42, 35, 46, 41, 48, 22, 1, 6, 26, 37, 27, 1, 6, 16, 48, 44, 46, 42, 41, 26, 1, 6, 28, 1, 6, 35, 43, 44, 43, 51, 36, 50, 49, 44, 46, 42, 50, 41, 27, 1, 6, 16, 1, 6, 10, 1, 6, 22, 1, 6, 15, 1, 6, 41, 27, 1, 6, 27, 36, 38, 37, 45, 53, 46, 45, 36, 42, 43, 20, 1, 6, 27, 1, 6, 38, 42, 24, 1, 6, 18, 1, 6, 47, 39, 38, 41, 42, 44, 41, 36, 44, 54, 39, 48, 51, 55, 44, 43, 20, 1, 6, 33, 1, 6, 45, 50, 50, 46, 48, 37, 51, 43, 45, 46, 43, 45, 29, 1, 6, 13, 43, 37, 39, 43, 44, 46, 50, 51, 17, 1, 6, 29, 46, 46, 53, 50, 46, 48, 46, 8, 43, 47, 52, 46, 43, 28, 1, 15, 1, 22, 1, 7, 40, 54, 1, 6, 19, 1, 7, 40, 49, 43, 52, 44, 52, 47, 45, 41, 52, 44, 47, 38, 37, 44, 48, 46, 16, 1, 6, 27, 1, 7, 18, 1, 6, 43, 41, 42, 49, 40, 48, 30, 1, 8, 1, 6, 24, 39, 42, 24, 1, 10, 1, 1, 1, 7, 1, 23, 1, 37, 1, 9, 58, 25, 1, 9, 63, 56, 1, 9, 64, 1, 9, 20, 1, 9, 59, 65, 62, 38, 1, 9, 37, 1, 9, 58, 65, 65, 63, 55, 1, 9, 17, 1, 9, 38, 1, 9, 52, 66, 1, 9, 58, 66, 61, 66, 27, 1, 9, 20, 1, 9, 38, 1, 9, 18, 1, 9, 61, 64, 6

Find sum of each line, mean, median and standard deviation of all lines in the file.

In [3]:
import math
sum=0

for i in list2:
    sum+=i
    
print("sum ",sum)

length = len(list2)
mean=sum/length
print("mean ",mean)

list2.sort()
median=int((list2[int(length/2)]+list2[int((length-1)/2)])/2)
print("median ",median)

sum2=0
for i in range(length):
    sum2+=(mean-list2[i])**2
sd=math.sqrt(int(sum2/length))

print("sd ",sd)

sum  173948
mean  25.69394387001477
median  25
sd  21.02379604162864

Count the number of words in the file

In [4]:
list4=[]
sum=0

with open('poem.txt','r') as f:
    for i in f.readlines():
        sum+=len(i.strip().split(' '))
sum

33123

Print the first 1000 characters from poem.txt.

In [8]:
list6=[]
with open('poem.txt','r') as f:
    for i in f.readlines():
        list6.extend(i.strip().split(' '))

list6[:1000]

['ï»¿XXXX',
 'HAMLET,',
 'PRINCE',
 'OF',
 'DENMARK',
 '',
 'by',
 'William',
 'Shakespeare',
 '',
 '',
 '',
 '',
 'PERSONS',
 'REPRESENTED.',
 '',
 'Claudius,',
 'King',
 'of',
 'Denmark.',
 'Hamlet,',
 'Son',
 'to',
 'the',
 'former,',
 'and',
 'Nephew',
 'to',
 'the',
 'present',
 'King.',
 'Polonius,',
 'Lord',
 'Chamberlain.',
 'Horatio,',
 'Friend',
 'to',
 'Hamlet.',
 'Laertes,',
 'Son',
 'to',
 'Polonius.',
 'Voltimand,',
 'Courtier.',
 'Cornelius,',
 'Courtier.',
 'Rosencrantz,',
 'Courtier.',
 'Guildenstern,',
 'Courtier.',
 'Osric,',
 'Courtier.',
 'A',
 'Gentleman,',
 'Courtier.',
 'A',
 'Priest.',
 'Marcellus,',
 'Officer.',
 'Bernardo,',
 'Officer.',
 'Francisco,',
 'a',
 'Soldier',
 'Reynaldo,',
 'Servant',
 'to',
 'Polonius.',
 'Players.',
 'Two',
 'Clowns,',
 'Grave-diggers.',
 'Fortinbras,',
 'Prince',
 'of',
 'Norway.',
 'A',
 'Captain.',
 'English',
 'Ambassadors.',
 'Ghost',
 'of',
 "Hamlet's",
 'Father.',
 '',
 'Gertrude,',
 'Queen',
 'of',
 'Denmark,',
 'and',
 'Mother',
 'of',
 'Hamlet.',
 'Ophelia,',
 'Daughter',
 'to',
 'Polonius.',
 '',
 'Lords,',
 'Ladies,',
 'Officers,',
 'Soldiers,',
 'Sailors,',
 'Messengers,',
 'and',
 'other',
 'Attendants.',
 '',
 'SCENE.',
 'Elsinore.',
 '',
 '',
 '',
 'ACT',
 'I.',
 '',
 'Scene',
 'I.',
 'Elsinore.',
 'A',
 'platform',
 'before',
 'the',
 'Castle.',
 '',
 '[Francisco',
 'at',
 'his',
 'post.',
 'Enter',
 'to',
 'him',
 'Bernardo.]',
 '',
 'Ber.',
 "Who's",
 'there?',
 '',
 'Fran.',
 'Nay,',
 'answer',
 'me:',
 'stand,',
 'and',
 'unfold',
 'yourself.',
 '',
 'Ber.',
 'Long',
 'live',
 'the',
 'king!',
 '',
 'Fran.',
 'Bernardo?',
 '',
 'Ber.',
 'He.',
 '',
 'Fran.',
 'You',
 'come',
 'most',
 'carefully',
 'upon',
 'your',
 'hour.',
 '',
 'Ber.',
 "'Tis",
 'now',
 'struck',
 'twelve.',
 'Get',
 'thee',
 'to',
 'bed,',
 'Francisco.',
 '',
 'Fran.',
 'For',
 'this',
 'relief',
 'much',
 'thanks:',
 "'tis",
 'bitter',
 'cold,',
 'And',
 'I',
 'am',
 'sick',
 'at',
 'heart.',
 '',
 'Ber.',
 'Have',
 'you',
 'had',
 'quiet',
 'guard?',
 '',
 'Fran.',
 'Not',
 'a',
 'mouse',
 'stirring.',
 '',
 'Ber.',
 'Well,',
 'good',
 'night.',
 'If',
 'you',
 'do',
 'meet',
 'Horatio',
 'and',
 'Marcellus,',
 'The',
 'rivals',
 'of',
 'my',
 'watch,',
 'bid',
 'them',
 'make',
 'haste.',
 '',
 'Fran.',
 'I',
 'think',
 'I',
 'hear',
 'them.--Stand,',
 'ho!',
 'Who',
 'is',
 'there?',
 '',
 '[Enter',
 'Horatio',
 'and',
 'Marcellus.]',
 '',
 'Hor.',
 'Friends',
 'to',
 'this',
 'ground.',
 '',
 'Mar.',
 'And',
 'liegemen',
 'to',
 'the',
 'Dane.',
 '',
 'Fran.',
 'Give',
 'you',
 'good-night.',
 '',
 'Mar.',
 'O,',
 'farewell,',
 'honest',
 'soldier;',
 'Who',
 'hath',
 "reliev'd",
 'you?',
 '',
 'Fran.',
 'Bernardo',
 'has',
 'my',
 'place.',
 'Give',
 'you',
 'good-night.',
 '',
 '[Exit.]',
 '',
 'Mar.',
 'Holla!',
 'Bernardo!',
 '',
 'Ber.',
 'Say.',
 'What,',
 'is',
 'Horatio',
 'there?',
 '',
 'Hor.',
 'A',
 'piece',
 'of',
 'him.',
 '',
 'Ber.',
 'Welcome,',
 'Horatio:--Welcome,',
 'good',
 'Marcellus.',
 '',
 'Mar.',
 'What,',
 'has',
 'this',
 'thing',
 "appear'd",
 'again',
 'to-night?',
 '',
 'Ber.',
 'I',
 'have',
 'seen',
 'nothing.',
 '',
 'Mar.',
 'Horatio',
 'says',
 "'tis",
 'but',
 'our',
 'fantasy,',
 'And',
 'will',
 'not',
 'let',
 'belief',
 'take',
 'hold',
 'of',
 'him',
 'Touching',
 'this',
 'dreaded',
 'sight,',
 'twice',
 'seen',
 'of',
 'us:',
 'Therefore',
 'I',
 'have',
 'entreated',
 'him',
 'along',
 'With',
 'us',
 'to',
 'watch',
 'the',
 'minutes',
 'of',
 'this',
 'night;',
 'That,',
 'if',
 'again',
 'this',
 'apparition',
 'come',
 'He',
 'may',
 'approve',
 'our',
 'eyes',
 'and',
 'speak',
 'to',
 'it.',
 '',
 'Hor.',
 'Tush,',
 'tush,',
 "'twill",
 'not',
 'appear.',
 '',
 'Ber.',
 'Sit',
 'down',
 'awhile,',
 'And',
 'let',
 'us',
 'once',
 'again',
 'assail',
 'your',
 'ears,',
 'That',
 'are',
 'so',
 'fortified',
 'against',
 'our',
 'story,',
 'What',
 'we',
 'two',
 'nights',
 'have',
 'seen.',
 '',
 'Hor.',
 'Well,',
 'sit',
 'we',
 'down,',
 'And',
 'let',
 'us',
 'hear',
 'Bernardo',
 'speak',
 'of',
 'this.',
 '',
 'Ber.',
 'Last',
 'night',
 'of',
 'all,',
 'When',
 'yond',
 'same',
 'star',
 "that's",
 'westward',
 'from',
 'the',
 'pole',
 'Had',
 'made',
 'his',
 'course',
 'to',
 'illume',
 'that',
 'part',
 'of',
 'heaven',
 'Where',
 'now',
 'it',
 'burns,',
 'Marcellus',
 'and',
 'myself,',
 'The',
 'bell',
 'then',
 'beating',
 'one,--',
 '',
 'Mar.',
 'Peace,',
 'break',
 'thee',
 'off;',
 'look',
 'where',
 'it',
 'comes',
 'again!',
 '',
 '[Enter',
 'Ghost,',
 'armed.]',
 '',
 'Ber.',
 'In',
 'the',
 'same',
 'figure,',
 'like',
 'the',
 'king',
 "that's",
 'dead.',
 '',
 'Mar.',
 'Thou',
 'art',
 'a',
 'scholar;',
 'speak',
 'to',
 'it,',
 'Horatio.',
 '',
 'Ber.',
 'Looks',
 'it',
 'not',
 'like',
 'the',
 'King?',
 'mark',
 'it,',
 'Horatio.',
 '',
 'Hor.',
 'Most',
 'like:--it',
 'harrows',
 'me',
 'with',
 'fear',
 'and',
 'wonder.',
 '',
 'Ber.',
 'It',
 'would',
 'be',
 'spoke',
 'to.',
 '',
 'Mar.',
 'Question',
 'it,',
 'Horatio.',
 '',
 'Hor.',
 'What',
 'art',
 'thou,',
 'that',
 "usurp'st",
 'this',
 'time',
 'of',
 'night,',
 'Together',
 'with',
 'that',
 'fair',
 'and',
 'warlike',
 'form',
 'In',
 'which',
 'the',
 'majesty',
 'of',
 'buried',
 'Denmark',
 'Did',
 'sometimes',
 'march?',
 'By',
 'heaven',
 'I',
 'charge',
 'thee,',
 'speak!',
 '',
 'Mar.',
 'It',
 'is',
 'offended.',
 '',
 'Ber.',
 'See,',
 'it',
 'stalks',
 'away!',
 '',
 'Hor.',
 'Stay!',
 'speak,',
 'speak!',
 'I',
 'charge',
 'thee',
 'speak!',
 '',
 '[Exit',
 'Ghost.]',
 '',
 'Mar.',
 "'Tis",
 'gone,',
 'and',
 'will',
 'not',
 'answer.',
 '',
 'Ber.',
 'How',
 'now,',
 'Horatio!',
 'You',
 'tremble',
 'and',
 'look',
 'pale:',
 'Is',
 'not',
 'this',
 'something',
 'more',
 'than',
 'fantasy?',
 'What',
 'think',
 'you',
 "on't?",
 '',
 'Hor.',
 'Before',
 'my',
 'God,',
 'I',
 'might',
 'not',
 'this',
 'believe',
 'Without',
 'the',
 'sensible',
 'and',
 'true',
 'avouch',
 'Of',
 'mine',
 'own',
 'eyes.',
 '',
 'Mar.',
 'Is',
 'it',
 'not',
 'like',
 'the',
 'King?',
 '',
 'Hor.',
 'As',
 'thou',
 'art',
 'to',
 'thyself:',
 'Such',
 'was',
 'the',
 'very',
 'armour',
 'he',
 'had',
 'on',
 'When',
 'he',
 'the',
 'ambitious',
 'Norway',
 'combated;',
 'So',
 "frown'd",
 'he',
 'once',
 'when,',
 'in',
 'an',
 'angry',
 'parle,',
 'He',
 'smote',
 'the',
 'sledded',
 'Polacks',
 'on',
 'the',
 'ice.',
 "'Tis",
 'strange.',
 '',
 'Mar.',
 'Thus',
 'twice',
 'before,',
 'and',
 'jump',
 'at',
 'this',
 'dead',
 'hour,',
 'With',
 'martial',
 'stalk',
 'hath',
 'he',
 'gone',
 'by',
 'our',
 'watch.',
 '',
 'Hor.',
 'In',
 'what',
 'particular',
 'thought',
 'to',
 'work',
 'I',
 'know',
 'not;',
 'But,',
 'in',
 'the',
 'gross',
 'and',
 'scope',
 'of',
 'my',
 'opinion,',
 'This',
 'bodes',
 'some',
 'strange',
 'eruption',
 'to',
 'our',
 'state.',
 '',
 'Mar.',
 'Good',
 'now,',
 'sit',
 'down,',
 'and',
 'tell',
 'me,',
 'he',
 'that',
 'knows,',
 'Why',
 'this',
 'same',
 'strict',
 'and',
 'most',
 'observant',
 'watch',
 'So',
 'nightly',
 'toils',
 'the',
 'subject',
 'of',
 'the',
 'land;',
 'And',
 'why',
 'such',
 'daily',
 'cast',
 'of',
 'brazen',
 'cannon,',
 'And',
 'foreign',
 'mart',
 'for',
 'implements',
 'of',
 'war;',
 'Why',
 'such',
 'impress',
 'of',
 'shipwrights,',
 'whose',
 'sore',
 'task',
 'Does',
 'not',
 'divide',
 'the',
 'Sunday',
 'from',
 'the',
 'week;',
 'What',
 'might',
 'be',
 'toward,',
 'that',
 'this',
 'sweaty',
 'haste',
 'Doth',
 'make',
 'the',
 'night',
 'joint-labourer',
 'with',
 'the',
 'day:',
 'Who',
 "is't",
 'that',
 'can',
 'inform',
 'me?',
 '',
 'Hor.',
 'That',
 'can',
 'I;',
 'At',
 'least,',
 'the',
 'whisper',
 'goes',
 'so.',
 'Our',
 'last',
 'king,',
 'Whose',
 'image',
 'even',
 'but',
 'now',
 "appear'd",
 'to',
 'us,',
 'Was,',
 'as',
 'you',
 'know,',
 'by',
 'Fortinbras',
 'of',
 'Norway,',
 'Thereto',
 "prick'd",
 'on',
 'by',
 'a',
 'most',
 'emulate',
 'pride,',
 "Dar'd",
 'to',
 'the',
 'combat;',
 'in',
 'which',
 'our',
 'valiant',
 'Hamlet,--',
 'For',
 'so',
 'this',
 'side',
 'of',
 'our',
 'known',
 'world',
 "esteem'd",
 'him,--',
 'Did',
 'slay',
 'this',
 'Fortinbras;',
 'who,',
 'by',
 'a',
 "seal'd",
 'compact,',
 'Well',
 'ratified',
 'by',
 'law',
 'and',
 'heraldry,',
 'Did',
 'forfeit,',
 'with',
 'his',
 'life,',
 'all',
 'those',
 'his',
 'lands,',
 'Which',
 'he',
 'stood',
 "seiz'd",
 'of,',
 'to',
 'the',
 'conqueror:',
 'Against',
 'the',
 'which,',
 'a',
 'moiety',
 'competent',
 'Was',
 'gaged',
 'by',
 'our',
 'king;',
 'which',
 'had',
 "return'd",
 'To',
 'the',
 'inheritance',
 'of',
 'Fortinbras,',
 'Had',
 'he',
 'been',
 'vanquisher;',
 'as',
 'by',
 'the',
 'same',
 "cov'nant,",
 'And',
 'carriage',
 'of',
 'the',
 'article',
 "design'd,",
 'His',
 'fell',
 'to',
 'Hamlet.',
 'Now,',
 'sir,',
 'young',
 'Fortinbras,',
 'Of',
 'unimproved',
 'mettle',
 'hot',
 'and',
 'full,',
 'Hath',
 'in',
 'the',
 'skirts',
 'of',
 'Norway,',
 'here',
 'and',
 'there,',
 "Shark'd",
 'up',
 'a',
 'list',
 'of',
 'lawless',
 'resolutes,',
 'For',
 'food',
 'and',
 'diet,',
 'to',
 'some',
 'enterprise',
 'That',
 'hath',
 'a',
 'stomach',
 "in't;",
 'which',
 'is',
 'no',
 'other,--',
 'As',
 'it',
 'doth',
 'well',
 'appear',
 'unto',
 'our',
 'state,--',
 'But',
 'to',
 'recover',
 'of',
 'us,',
 'by',
 'strong',
 'hand,',
 'And',
 'terms',
 'compulsatory,']

Print the 3rd to 5th words from the file.

In [9]:
list6[3:6]

['OF', 'DENMARK', '']

Get every third word between the second and the 15th words.

In [10]:
list6[3:15:3]

['OF', 'by', '', '']

Print the last word from the file and change the second last characted in the string to 'g'.

In [14]:
print(list6[-1])
list6[-1][-2]='g'
#error

off.]

TypeError: 'str' object does not support item assignment

State if the above operation completed successfully. State reasons

'str' object does not support item assignment

# Find types of Python variables and functions

In [15]:
type("This is a string")

str

Find what are the types of the following and state if they are mutable of immutable

In [18]:
print(type(None)) # immutable
print(type(1)) # immutable
print(type(1.0))# immutable
print(type(add))# immutable
print(type((1, 'a', 3, 'b')))# immutable
print(type([1, 'a', 3, 'b']))# mutable

<class 'NoneType'>
<class 'int'>
<class 'float'>
<class 'function'>
<class 'tuple'>
<class 'list'>

Append new elements at the end of a list

In [18]:
list1 = [1, 2, 3, 4, 5]
list1.append(2)
list1

[1, 2, 3, 4, 5, 2]

Loop through each element of the list

In [19]:
for i in list1:
    print(i,end=' ')

1 2 3 4 5 2

Use a indexing operator

In [21]:
for i in range(len(list1)):
    print(list1[i],end=' ')

1 2 3 4 5 2

Concatenate two lists

In [22]:
list2=[3,4,5]
l_concat=list1+list2

l_concat

[1, 2, 3, 4, 5, 2, 3, 4, 5]

Use * to repeat lists

In [24]:
list1 = list1*2
list1

[1, 2, 3, 4, 5, 2, 1, 2, 3, 4, 5, 2]

Use the in operator to check if something is in a list

In [27]:
if 1 in list1:
    print('present')

present

Initialize a string and slice the first 1, 2 and 3 characters. Then from 3rd to end.

In [28]:
str1 = 'My name is Rushikesh Shimpi'
print(str1[:3])
print(str1[3:])

My
name is Rushikesh Shimpi

Take a first name and a last name and then concatenate the last name with 3 times the first name and show result.

In [30]:
str1='Rushikesh'
str2='Shimpi'

s = str1*3 + str2
s

'RushikeshRushikeshRushikeshShimpi'

Take a string with four words. Use the split function to display the second and the last words

In [31]:
s='My name is Rushikesh'.split(' ')
print(s[1])
print(s[-1])

name
Rushikesh

Concatenate a number with a string. Update following:

In [33]:
'Data'+str(2)

'Data2'

## Dictionaries associated with lists

Create a list of keys and values

In [34]:
x = {'DSB': 'dsb@iiitg', 'Rakesh': 'rakesh@iiitg'}
x['DSB']

'dsb@iiitg'

In [35]:
x['GB'] = None

Iterate over all the keys

In [36]:
for i in x.keys():
    print(i)

DSB
Rakesh
GB

Iterate over all the values

In [37]:
for i in x.values():
    print(i)

dsb@iiitg
rakesh@iiitg
None

Iterate over all the key-vlaue pairs in the list

In [38]:
for i,j in zip(x.keys(),x.values()):
    print(i,j)

DSB dsb@iiitg
Rakesh rakesh@iiitg
GB None

Unpack the following sequence into different variables

In [40]:
x=('DSB','IIITG','dsb@iiitg','CSE')
a1, a2, a3, a4 = x
print(a1, a2, a3, a4)

DSB IIITG dsb@iiitg CSE

Use Python's in-built methods for string formatting

In [41]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'DSB'}

sales_statement = '{} got {} item(s) at a cost of {} each for a total of {}'.format(sales_record['person'],sales_record['num_items'],sales_record['price'],sales_record['num_items']*sales_record['price'])

print(sales_statement)

DSB got 4 item(s) at a cost of 3.24 each for a total of 12.96

Take a list of 10 elements and convert into json using  json library. Demonstrate use of loads and dumps

In [44]:
import json
dictionary ={
    'first name':'Rushikesh',
    'Last name':'Shimpi',
    'clg':'IIITG',
    'Dept':'CSE',
    'loc':'Nashik',
    'pin' : '422006',
    'state' : 'maharashtra',
    'country' : 'india',
    'ph number' : '89********',
    'occupation' : 'student'
}
x = json.dumps(dictionary)
print(x)
y = json.loads(x)
print(y['first name'])

{"first name": "Rushikesh", "Last name": "Shimpi", "clg": "IIITG", "Dept": "CSE", "loc": "Nashik", "pin": "422006", "state": "maharashtra", "country": "india", "ph number": "89********", "occupation": "student"}
Rushikesh

# Python objects and functions

Take the following code:

In [46]:
class students:
    dept = "Department of CSE"
    def assign_name(self, n):
        self.name = n
    def assign_location(self, l):
        self.location = l

Create a object of the class above. Set name and location of your choice.

In [48]:
st = students()
st.assign_name('Rushikesh Shimpi')
st.assign_location('Nashik, Maharashtra, India')

Format accordingly and print in a manner so we see something like : "Dip Sankar lives in Guwahati, Assam, India and works in the Department of CSE". The name and location should be of your choice. Use 1 print only

In [50]:
'{} lives in {} and is a student at IIITG in {}'.format(st.name,st.location,st.dept)

'Rushikesh Shimpi lives in Nashik, Maharashtra, India and is a student at IIITG in Department of CSE'

Create two lists of 5 elements each. Map the min function to the lists using map(). Print the minimum object.

In [51]:
l1 = [1,2,3,4,5]
l2 = [11, 12, 13, 14, 15]

def min_func(a,b):
    return min(a,b)

map1 = map(min_func,l1,l2)

iterator=iter(map1)

list10=[]

for i in range(len(l1)):
    list10.append(next(iterator))

list10

[1, 2, 3, 4, 5]

Iterate through that object and print the elements.

In [53]:
for i in list10:
    print(i,end=' ')

1 2 3 4 5

# Working with CSV

Let's import a file with fuel economy data

In [54]:
import csv
with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv', 'f'),
              ('cty', '20'),
              ('hwy', '31'),
              ('fl', 'p'),
              ('class', 'compact')])]

Find out how many items are there in the dictionary

In [55]:
len(mpg)

234

Find the column names with keys

In [56]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

Find the average cty fuel economy across all cars. All values in the dictionaries are strings.

In [57]:
sum=0
for i in range(len(mpg)):
    sum = sum + int(mpg[i]['cty'])
    
average=sum/len(mpg)

print(average)

16.858974358974358

Find the average hwy fuel economy across all cars

In [58]:
sum1=0

for i in range(len(mpg)):
    sum1 = sum1 + int(mpg[i]['hwy'])
    
average1 = sum1/len(mpg)

print(average1)

23.44017094017094

Use set to return the unique values for the number of cylinders the cars.

In [62]:
cylinders=[]

for i in range(len(mpg)):
    cylinders.append(mpg[i]['cyl'])
    
set(cylinders)

{'4', '5', '6', '8'}

Group the cars by number of cylinder, and finding the average cty mpg for each group.

In [63]:
MpgByCyl = []

for i in cylinders: # iterate over all the cylinder levels
    sumpg = 0
    typecount = 0
    for d in mpg: # iterate over all dictionaries
        ##ADD REMAINING CODE
        if(d['cyl']==i):
            typecount+=1
            sumpg+=int(d['cty'])
    
    MpgByCyl.append((i,sumpg/typecount))

list(set(MpgByCyl))

[('5', 20.5),
 ('6', 16.21518987341772),
 ('4', 21.012345679012345),
 ('8', 12.571428571428571)]

Return the unique values for the class types in our dataset using set.

In [64]:
vehicleclass = set(d['class'] for d in mpg)

Find average miles per gallon in the highway for each class of vehicles

In [65]:
MileageByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    sumpg = 0
    classCount = 0
    for d in mpg: # iterate over all dictionaries
        ##ADD REST OF THE CODE
        sumpg+=float(d['displ'])
        classCount+=1
    
    MileageByClass.append((t,sumpg/classCount))

print(MileageByClass)

[('midsize', 3.4717948717948697), ('minivan', 3.4717948717948697), ('subcompact', 3.4717948717948697), ('pickup', 3.4717948717948697), ('compact', 3.4717948717948697), ('2seater', 3.4717948717948697), ('suv', 3.4717948717948697)]